//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1_Temperature.TempConversionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempConversionService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/C2F", ReplyAction="http://tempuri.org/IService1/C2FResponse")]
        double C2F(double celsiusTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/C2F", ReplyAction="http://tempuri.org/IService1/C2FResponse")]
        System.Threading.Tasks.Task<double> C2FAsync(double celsiusTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/F2C", ReplyAction="http://tempuri.org/IService1/F2CResponse")]
        double F2C(double fahrenheitTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/F2C", ReplyAction="http://tempuri.org/IService1/F2CResponse")]
        System.Threading.Tasks.Task<double> F2CAsync(double fahrenheitTemp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApplication1_Temperature.TempConversionService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApplication1_Temperature.TempConversionService.IService1>, WindowsFormsApplication1_Temperature.TempConversionService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double C2F(double celsiusTemp) {
            return base.Channel.C2F(celsiusTemp);
        }
        
        public System.Threading.Tasks.Task<double> C2FAsync(double celsiusTemp) {
            return base.Channel.C2FAsync(celsiusTemp);
        }
        
        public double F2C(double fahrenheitTemp) {
            return base.Channel.F2C(fahrenheitTemp);
        }
        
        public System.Threading.Tasks.Task<double> F2CAsync(double fahrenheitTemp) {
            return base.Channel.F2CAsync(fahrenheitTemp);
        }
    }
}
